### ISSUE TITLE
Dataset is missing

### ISSUE THREAD

**Issue by hoaghiepp** [OdyAsh/Handwritten-M2L#1]
https://drive.google.com/drive/folders/1G44LpOZjIL19jOgHQgBr_r77fdMOkS_0?usp=sharing. I opened it and there was nothing in it. Please upload dataset again. Thank you very much.

**Comment by OdyAsh** [comment]
Unfortunately, this project hasn't been maintained for a long time, BUT, if I remember correctly, we used this dataset 🙌

[https://www.kaggle.com/datasets/xainano/handwrittenmathsymbols](https://www.kaggle.com/datasets/xainano/handwrittenmathsymbols)
